---
grafana_url: "https://grafana.sec.lan:3000"
grafana_admin_user: admin
grafana_admin_password: ""    # ← injecté depuis Vault

# Datasource OpenSearch en lecture seule sur l'indexer Wazuh
wazuh_indexer_url: "https://wazuh.sec.lan:9200"
wazuh_indexer_index: "wazuh-alerts-*"
wazuh_indexer_user: "readonly"
wazuh_indexer_password: ""    # ← injecté depuis Vault
