---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml

driver:
  name: docker

platforms:
  - name: instance-debian12
    image: debian:bookworm
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
      stdout_callback: default
  inventory:
    host_vars:
      instance-debian12:
        host_allowed_ports:
          - { port: 1514, proto: tcp, source: "192.168.20.0/24", comment: "wazuh agent" }

verifier:
  name: ansible
