---
- name: reload prometheus
  ansible.builtin.command:
    cmd: docker restart prometheus
  changed_when: true
  failed_when: false

- name: restart grafana
  ansible.builtin.command:
    cmd: docker restart grafana
  changed_when: true
  failed_when: false
